mkdir build
cd build

if [[ "$target_platform" == linux-* ]]; then
    BUILD_NINJAFOAM=True
else
    BUILD_NINJAFOAM=False
fi

cmake ${CMAKE_ARGS} \
  -DCMAKE_PREFIX_PATH:PATH=${PREFIX} \
  -DCMAKE_INSTALL_PREFIX:PATH=${PREFIX} \
  -DCMAKE_INSTALL_LIBDIR=lib \
  -DCMAKE_BUILD_TYPE=Release \
  -DCMAKE_POLICY_VERSION_MINIMUM=3.5 \
  -DNINJA_QTGUI=False \
  -DNINJAFOAM=${BUILD_NINJAFOAM} \
  -DCMAKE_CXX_STANDARD=11 \
  -DOPENMP_SUPPORT=True \
  -DBUILD_FETCH_DEM=False \
  -DBUILD_STL_CONVERTER=False \
  -DBUILD_CONVERT_OUTPUT=False \
  -DBUILD_SOLAR_GRID=False \
  ..

make -j${CPU_COUNT} install
