{% set name = "windninja" %}
{% set version = "3.12.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/firelab/windninja/archive/refs/tags/{{ version }}.tar.gz
  sha256: c6a0bf3e79a7dca875f9c1bcec6b3b625192bdd6cebcfdfb1fc6c30def4bea63
  patches:
    - patch-CPLIsNan.patch
    - patch-CPLCreateJoinableThread.patch

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - cmake
    - make
  host:
    - libboost-devel
    - libgdal
    - libnetcdf


test:
  commands:
    - test -f ${PREFIX}/bin/WindNinja_cli


about:
  home: https://github.com/firelab/windninja
  doc_url: https://weather.firelab.org/windninja/tutorials/
  summary: 'A diagnostic wind model developed for use in wildland fire modeling. '
  description: |
    WindNinja is a diagnostic wind model developed for use in wildland fire modeling.
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt


extra:
  recipe-maintainers:
    - Chrismarsh
    - nwagenbrenner
