{% set name = "windninja" %}
{% set version = "3.11.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/firelab/windninja/archive/refs/tags/{{ version }}.tar.gz
  sha256: c9b9af0c9905d8a0792ccf9db9958a0e3b201f653336fd59dbc7f5679cb79881

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - cmake
    - make
  host:
    - libboost-devel
    - libgdal
    - libnetcdf


test:
  commands:
    - test -f ${PREFIX}/bin/WindNinja_cli


about:
  home: https://github.com/firelab/windninja
  doc_url: https://weather.firelab.org/windninja/tutorials/
  summary: 'A diagnostic wind model developed for use in wildland fire modeling. '
  description: |
    WindNinja is a diagnostic wind model developed for use in wildland fire modeling.
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt


extra:
  recipe-maintainers:
    - Chrismarsh
    - nwagenbrenner
